# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'
target 'UCloudRtcSdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'UCloudRtcSdk', :path => '../../' 
#  pod 'UCloudRtcSdk'
 pod 'UCloudRtcSdk', '~> 1.5.8'
end
