# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'
target 'UCloudRtcSdk-ios-demo' do
  use_frameworks!
  # pod 'UCloudRtcSdk', :path => '../../'
   pod 'UCloudRtcSdk'
  # Pods for UCloudRtcSdk-ios-demo

end
